[package]
name = "perfect-flow"
version = "0.1.0"
authors = ["Solonarv <nstamm@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.3"