name:                perfect-flow
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/Solonarv/perfect-flow#readme
github:              Solonarv/perfect-flow
license:             MIT
author:              Solonarv
maintainer:          nstamm@gmx.de
copyright:           2018 Solonarv
category:            Game
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - apecs
  - sdl2
  - sdl2-ttf
  - text
  - yaml
  - aeson
  - scientific
  - vector
  - containers
  - hashable
  - unordered-containers
  - mtl
  - transformers
  - filepath
  - directory
  - lens
  - linear
  - StateVar
  - unliftio
  - data-default
  - deepseq
  - template-haskell

executables:
  perfect-flow:
    source-dirs:      src
    main:             Main.hs
    dependencies:
      - sdl-apecs-ui
      - apecs-extra
      - sdl-extra

# Empty for now
library: {}

internal-libraries:
  sdl-apecs-ui:
    source-dirs:      sdl-apecs-ui
    dependencies:
      - apecs-extra
  apecs-extra:
    source-dirs:      apecs-extra
  sdl-extra:
    source-dirs:      sdl-extra


default-extensions: &extensions
  - LambdaCase
  - PatternSynonyms
  - GeneralizedNewtypeDeriving
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - ScopedTypeVariables
  - GADTs
  - TypeFamilies
  - RankNTypes
  - ViewPatterns
  - TypeApplications
  - MultiParamTypeClasses
  - FlexibleContexts
  - ConstraintKinds
  - TypeOperators
  - DataKinds
  - TupleSections