name:                util-lib
version:             0.1.0.0
#synopsis:
#description:
github:              Solonarv/perfect-flow
license:             MIT
author:              Solonarv
maintainer:          nstamm@gmx.de
copyright:           2018 Solonarv
category:            Game
# extra-source-files:
# - README.md

dependencies:
  - base >= 4.7 && < 5
  - apecs
  - mtl
  - hashable
  - unordered-containers
  - StateVar
  - fast-logger
  - unliftio

library:
  source-dirs: .

default-extensions: &extensions
  - LambdaCase
  - PatternSynonyms
  - GeneralizedNewtypeDeriving
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DeriveGeneric
  - ScopedTypeVariables
  - GADTs
  - TypeFamilies
  - RankNTypes
  - ViewPatterns
  - TypeApplications
  - MultiParamTypeClasses
  - FlexibleContexts
  - FlexibleInstances
  - ConstraintKinds
  - TypeOperators
  - DataKinds
  - TupleSections
  - FunctionalDependencies
  - ExistentialQuantification