name:                sdl-extra
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://gitlab.com/Solonarv/perfect-flow#readme
license:             MIT
author:              Solonarv
maintainer:          nstamm@gmx.de
copyright:           2018 Solonarv
category:            Game
# extra-source-files:
# - README.md

dependencies:
  - base >= 4.7 && < 5
  - apecs
  - hashable
  - sdl2
  - sdl2-ttf
  - linear
  - mtl
  - vector
  - StateVar
  - text
  - lens
  - util-lib

library:
  source-dirs: .

default-extensions: &extensions
  - LambdaCase
  - PatternSynonyms
  - GeneralizedNewtypeDeriving
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DeriveGeneric
  - ScopedTypeVariables
  - GADTs
  - TypeFamilies
  - RankNTypes
  - ViewPatterns
  - TypeApplications
  - MultiParamTypeClasses
  - FlexibleContexts
  - FlexibleInstances
  - ConstraintKinds
  - TypeOperators
  - DataKinds
  - TupleSections
  - FunctionalDependencies
  - ExistentialQuantification